/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermeniRouteImport } from './routes/termeni'
import { Route as SurseleNoastreRouteImport } from './routes/sursele-noastre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SalvateRouteImport } from './routes/salvate'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PoliticaConfidentialitateRouteImport } from './routes/politica-confidentialitate'
import { Route as ParteneriRouteImport } from './routes/parteneri'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CumFunctioneazaRouteImport } from './routes/cum-functioneaza'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ActivitateRouteImport } from './routes/activitate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourceSourceIdRouteImport } from './routes/source.$sourceId'
import { Route as EventSlugRouteImport } from './routes/event.$slug'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermeniRoute = TermeniRouteImport.update({
  id: '/termeni',
  path: '/termeni',
  getParentRoute: () => rootRouteImport,
} as any)
const SurseleNoastreRoute = SurseleNoastreRouteImport.update({
  id: '/sursele-noastre',
  path: '/sursele-noastre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SalvateRoute = SalvateRouteImport.update({
  id: '/salvate',
  path: '/salvate',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaConfidentialitateRoute =
  PoliticaConfidentialitateRouteImport.update({
    id: '/politica-confidentialitate',
    path: '/politica-confidentialitate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParteneriRoute = ParteneriRouteImport.update({
  id: '/parteneri',
  path: '/parteneri',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CumFunctioneazaRoute = CumFunctioneazaRouteImport.update({
  id: '/cum-functioneaza',
  path: '/cum-functioneaza',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitateRoute = ActivitateRouteImport.update({
  id: '/activitate',
  path: '/activitate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceSourceIdRoute = SourceSourceIdRouteImport.update({
  id: '/source/$sourceId',
  path: '/source/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSlugRoute = EventSlugRouteImport.update({
  id: '/event/$slug',
  path: '/event/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/admin/review',
  path: '/admin/review',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/admin/pipeline',
  path: '/admin/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activitate': typeof ActivitateRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/cum-functioneaza': typeof CumFunctioneazaRoute
  '/dashboard': typeof DashboardRoute
  '/despre': typeof DespreRoute
  '/feed': typeof FeedRoute
  '/parteneri': typeof ParteneriRoute
  '/politica-confidentialitate': typeof PoliticaConfidentialitateRoute
  '/profil': typeof ProfilRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/salvate': typeof SalvateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sursele-noastre': typeof SurseleNoastreRoute
  '/termeni': typeof TermeniRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/review': typeof AdminReviewRoute
  '/event/$slug': typeof EventSlugRoute
  '/source/$sourceId': typeof SourceSourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activitate': typeof ActivitateRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/cum-functioneaza': typeof CumFunctioneazaRoute
  '/dashboard': typeof DashboardRoute
  '/despre': typeof DespreRoute
  '/feed': typeof FeedRoute
  '/parteneri': typeof ParteneriRoute
  '/politica-confidentialitate': typeof PoliticaConfidentialitateRoute
  '/profil': typeof ProfilRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/salvate': typeof SalvateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sursele-noastre': typeof SurseleNoastreRoute
  '/termeni': typeof TermeniRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/review': typeof AdminReviewRoute
  '/event/$slug': typeof EventSlugRoute
  '/source/$sourceId': typeof SourceSourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activitate': typeof ActivitateRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/cum-functioneaza': typeof CumFunctioneazaRoute
  '/dashboard': typeof DashboardRoute
  '/despre': typeof DespreRoute
  '/feed': typeof FeedRoute
  '/parteneri': typeof ParteneriRoute
  '/politica-confidentialitate': typeof PoliticaConfidentialitateRoute
  '/profil': typeof ProfilRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/salvate': typeof SalvateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sursele-noastre': typeof SurseleNoastreRoute
  '/termeni': typeof TermeniRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/review': typeof AdminReviewRoute
  '/event/$slug': typeof EventSlugRoute
  '/source/$sourceId': typeof SourceSourceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activitate'
    | '/bookmarks'
    | '/contact'
    | '/cum-functioneaza'
    | '/dashboard'
    | '/despre'
    | '/feed'
    | '/parteneri'
    | '/politica-confidentialitate'
    | '/profil'
    | '/quiz'
    | '/reset-password'
    | '/robots.txt'
    | '/salvate'
    | '/sitemap.xml'
    | '/sursele-noastre'
    | '/termeni'
    | '/unsubscribe'
    | '/admin/pipeline'
    | '/admin/review'
    | '/event/$slug'
    | '/source/$sourceId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activitate'
    | '/bookmarks'
    | '/contact'
    | '/cum-functioneaza'
    | '/dashboard'
    | '/despre'
    | '/feed'
    | '/parteneri'
    | '/politica-confidentialitate'
    | '/profil'
    | '/quiz'
    | '/reset-password'
    | '/robots.txt'
    | '/salvate'
    | '/sitemap.xml'
    | '/sursele-noastre'
    | '/termeni'
    | '/unsubscribe'
    | '/admin/pipeline'
    | '/admin/review'
    | '/event/$slug'
    | '/source/$sourceId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/activitate'
    | '/bookmarks'
    | '/contact'
    | '/cum-functioneaza'
    | '/dashboard'
    | '/despre'
    | '/feed'
    | '/parteneri'
    | '/politica-confidentialitate'
    | '/profil'
    | '/quiz'
    | '/reset-password'
    | '/robots.txt'
    | '/salvate'
    | '/sitemap.xml'
    | '/sursele-noastre'
    | '/termeni'
    | '/unsubscribe'
    | '/admin/pipeline'
    | '/admin/review'
    | '/event/$slug'
    | '/source/$sourceId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitateRoute: typeof ActivitateRoute
  BookmarksRoute: typeof BookmarksRoute
  ContactRoute: typeof ContactRoute
  CumFunctioneazaRoute: typeof CumFunctioneazaRoute
  DashboardRoute: typeof DashboardRoute
  DespreRoute: typeof DespreRoute
  FeedRoute: typeof FeedRoute
  ParteneriRoute: typeof ParteneriRoute
  PoliticaConfidentialitateRoute: typeof PoliticaConfidentialitateRoute
  ProfilRoute: typeof ProfilRoute
  QuizRoute: typeof QuizRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SalvateRoute: typeof SalvateRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SurseleNoastreRoute: typeof SurseleNoastreRoute
  TermeniRoute: typeof TermeniRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminReviewRoute: typeof AdminReviewRoute
  EventSlugRoute: typeof EventSlugRoute
  SourceSourceIdRoute: typeof SourceSourceIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni': {
      id: '/termeni'
      path: '/termeni'
      fullPath: '/termeni'
      preLoaderRoute: typeof TermeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sursele-noastre': {
      id: '/sursele-noastre'
      path: '/sursele-noastre'
      fullPath: '/sursele-noastre'
      preLoaderRoute: typeof SurseleNoastreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salvate': {
      id: '/salvate'
      path: '/salvate'
      fullPath: '/salvate'
      preLoaderRoute: typeof SalvateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-confidentialitate': {
      id: '/politica-confidentialitate'
      path: '/politica-confidentialitate'
      fullPath: '/politica-confidentialitate'
      preLoaderRoute: typeof PoliticaConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parteneri': {
      id: '/parteneri'
      path: '/parteneri'
      fullPath: '/parteneri'
      preLoaderRoute: typeof ParteneriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cum-functioneaza': {
      id: '/cum-functioneaza'
      path: '/cum-functioneaza'
      fullPath: '/cum-functioneaza'
      preLoaderRoute: typeof CumFunctioneazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activitate': {
      id: '/activitate'
      path: '/activitate'
      fullPath: '/activitate'
      preLoaderRoute: typeof ActivitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source/$sourceId': {
      id: '/source/$sourceId'
      path: '/source/$sourceId'
      fullPath: '/source/$sourceId'
      preLoaderRoute: typeof SourceSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$slug': {
      id: '/event/$slug'
      path: '/event/$slug'
      fullPath: '/event/$slug'
      preLoaderRoute: typeof EventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/admin/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/admin/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitateRoute: ActivitateRoute,
  BookmarksRoute: BookmarksRoute,
  ContactRoute: ContactRoute,
  CumFunctioneazaRoute: CumFunctioneazaRoute,
  DashboardRoute: DashboardRoute,
  DespreRoute: DespreRoute,
  FeedRoute: FeedRoute,
  ParteneriRoute: ParteneriRoute,
  PoliticaConfidentialitateRoute: PoliticaConfidentialitateRoute,
  ProfilRoute: ProfilRoute,
  QuizRoute: QuizRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SalvateRoute: SalvateRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SurseleNoastreRoute: SurseleNoastreRoute,
  TermeniRoute: TermeniRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminReviewRoute: AdminReviewRoute,
  EventSlugRoute: EventSlugRoute,
  SourceSourceIdRoute: SourceSourceIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
