export type TopicCatalogEntry = {
  slug: string;
  displayName: string;
  description: string;
  aliases: string[];
  keywords: string[];
  keyPhrases: string[];
  excludePhrases?: string[];
};

export const TOPIC_CATALOG: TopicCatalogEntry[] = [
  {
    slug: "world",
    displayName: "World",
    description: "International developments, diplomacy, and major cross-border events.",
    aliases: ["international news", "global affairs"],
    keywords: [
      "global",
      "international",
      "foreign",
      "overseas",
      "diplomacy",
      "allies",
      "summit",
      "sanctions",
    ],
    keyPhrases: [
      "foreign ministry",
      "international summit",
      "global leaders",
      "diplomatic talks",
    ],
  },
  {
    slug: "politics",
    displayName: "Politics",
    description: "Political leadership, parties, campaigns, and governing fights.",
    aliases: ["government politics", "political news"],
    keywords: [
      "president",
      "prime minister",
      "parliament",
      "congress",
      "senate",
      "house",
      "lawmakers",
      "campaign",
      "cabinet",
      "governor",
    ],
    keyPhrases: [
      "white house",
      "political party",
      "campaign trail",
      "coalition government",
    ],
  },
  {
    slug: "elections",
    displayName: "Elections",
    description: "Voting, ballots, polling, election administration, and campaign results.",
    aliases: ["voting", "campaign elections"],
    keywords: [
      "election",
      "elections",
      "vote",
      "voter",
      "ballot",
      "polling",
      "primary",
      "runoff",
      "referendum",
      "turnout",
    ],
    keyPhrases: [
      "election results",
      "polling station",
      "mail in ballot",
      "voter turnout",
    ],
  },
  {
    slug: "policy",
    displayName: "Policy",
    description: "Legislation, regulation, rulemaking, and public policy design.",
    aliases: ["public policy", "regulation"],
    keywords: [
      "bill",
      "legislation",
      "regulation",
      "regulatory",
      "policy",
      "mandate",
      "framework",
      "rule",
      "law",
      "proposal",
    ],
    keyPhrases: [
      "proposed rule",
      "regulatory framework",
      "policy proposal",
      "legislative package",
    ],
  },
  {
    slug: "courts",
    displayName: "Courts",
    description: "Judicial rulings, legal challenges, trials, and constitutional disputes.",
    aliases: ["judiciary", "legal system"],
    keywords: [
      "court",
      "judge",
      "justice",
      "lawsuit",
      "appeal",
      "ruling",
      "verdict",
      "trial",
      "supreme court",
      "injunction",
    ],
    keyPhrases: [
      "federal court",
      "court ruling",
      "legal challenge",
      "supreme court",
    ],
  },
  {
    slug: "immigration",
    displayName: "Immigration",
    description: "Border policy, visas, asylum, migration, and deportation issues.",
    aliases: ["border policy", "migration"],
    keywords: [
      "immigration",
      "migrant",
      "migrants",
      "border",
      "visa",
      "asylum",
      "deportation",
      "refugee",
      "customs",
      "detention",
    ],
    keyPhrases: [
      "border security",
      "asylum seekers",
      "immigration reform",
      "visa restrictions",
    ],
  },
  {
    slug: "economy",
    displayName: "Economy",
    description: "Inflation, growth, jobs, central banks, trade, and macroeconomic conditions.",
    aliases: ["economic news", "macroeconomy"],
    keywords: [
      "economy",
      "economic",
      "inflation",
      "gdp",
      "recession",
      "jobs",
      "employment",
      "unemployment",
      "trade",
      "tariff",
      "fed",
      "federal reserve",
      "interest rates",
    ],
    keyPhrases: [
      "consumer prices",
      "economic growth",
      "interest rate decision",
      "labor market",
      "central bank",
    ],
  },
  {
    slug: "business",
    displayName: "Business",
    description: "Corporate strategy, earnings, mergers, layoffs, and industry competition.",
    aliases: ["corporate news", "companies"],
    keywords: [
      "company",
      "companies",
      "corporate",
      "earnings",
      "revenue",
      "profit",
      "merger",
      "acquisition",
      "layoffs",
      "executive",
      "startup",
    ],
    keyPhrases: [
      "quarterly earnings",
      "merger agreement",
      "business strategy",
      "market share",
    ],
  },
  {
    slug: "markets",
    displayName: "Markets",
    description: "Stocks, bonds, currencies, commodities, and market volatility.",
    aliases: ["financial markets", "wall street"],
    keywords: [
      "stocks",
      "shares",
      "bond",
      "bonds",
      "yield",
      "markets",
      "wall street",
      "dow",
      "nasdaq",
      "s&p",
      "investors",
      "trading",
    ],
    keyPhrases: [
      "stock market",
      "treasury yields",
      "market rally",
      "market selloff",
    ],
    excludePhrases: ["housing market"],
  },
  {
    slug: "labor",
    displayName: "Labor",
    description: "Workers, unions, strikes, wages, and workplace regulation.",
    aliases: ["workforce", "workers"],
    keywords: [
      "union",
      "strike",
      "workers",
      "worker",
      "wages",
      "pay",
      "labor",
      "workforce",
      "collective bargaining",
      "walkout",
    ],
    keyPhrases: [
      "union contract",
      "labor dispute",
      "pay raise",
      "work stoppage",
    ],
  },
  {
    slug: "housing",
    displayName: "Housing",
    description: "Home prices, rents, mortgages, supply, and housing affordability.",
    aliases: ["real estate housing", "home affordability"],
    keywords: [
      "housing",
      "rent",
      "rents",
      "mortgage",
      "home prices",
      "real estate",
      "landlord",
      "tenant",
      "foreclosure",
      "zoning",
    ],
    keyPhrases: [
      "housing market",
      "mortgage rates",
      "home affordability",
      "rental market",
    ],
  },
  {
    slug: "tech",
    displayName: "Tech",
    description: "Technology platforms, software, hardware, internet companies, and digital products.",
    aliases: ["technology", "technology sector"],
    keywords: [
      "tech",
      "technology",
      "software",
      "hardware",
      "internet",
      "platform",
      "app",
      "apps",
      "device",
      "devices",
      "chip",
      "chips",
      "semiconductor",
    ],
    keyPhrases: [
      "technology sector",
      "software company",
      "consumer electronics",
      "silicon valley",
    ],
  },
  {
    slug: "ai",
    displayName: "AI",
    description: "Artificial intelligence models, tools, regulation, safety, and deployment.",
    aliases: ["artificial intelligence", "machine learning"],
    keywords: [
      "ai",
      "artificial intelligence",
      "machine learning",
      "llm",
      "chatbot",
      "model",
      "models",
      "training data",
      "compute",
      "deepfake",
      "automation",
    ],
    keyPhrases: [
      "ai model",
      "generative ai",
      "training data",
      "foundation model",
      "ai safety",
    ],
  },
  {
    slug: "cybersecurity",
    displayName: "Cybersecurity",
    description: "Hacks, breaches, malware, ransomware, and digital security.",
    aliases: ["cyber", "information security"],
    keywords: [
      "cybersecurity",
      "cyber",
      "hack",
      "hacker",
      "breach",
      "malware",
      "ransomware",
      "phishing",
      "exploit",
      "security flaw",
    ],
    keyPhrases: [
      "data breach",
      "cyber attack",
      "security vulnerability",
      "critical infrastructure",
    ],
  },
  {
    slug: "crypto",
    displayName: "Crypto",
    description: "Cryptocurrencies, blockchain markets, regulation, and digital assets.",
    aliases: ["cryptocurrency", "digital assets"],
    keywords: [
      "crypto",
      "cryptocurrency",
      "bitcoin",
      "ethereum",
      "blockchain",
      "token",
      "tokens",
      "stablecoin",
      "exchange",
      "digital asset",
    ],
    keyPhrases: [
      "crypto exchange",
      "digital asset regulation",
      "bitcoin price",
      "blockchain network",
    ],
  },
  {
    slug: "health",
    displayName: "Health",
    description: "Healthcare systems, disease outbreaks, medicines, hospitals, and public health.",
    aliases: ["public health", "healthcare"],
    keywords: [
      "health",
      "healthcare",
      "hospital",
      "hospitals",
      "doctor",
      "doctors",
      "patient",
      "patients",
      "vaccine",
      "outbreak",
      "disease",
      "medical",
    ],
    keyPhrases: [
      "public health",
      "healthcare system",
      "medical treatment",
      "disease outbreak",
    ],
  },
  {
    slug: "science",
    displayName: "Science",
    description: "Research, discovery, experiments, and scientific institutions.",
    aliases: ["research", "scientific research"],
    keywords: [
      "science",
      "scientists",
      "research",
      "study",
      "studies",
      "laboratory",
      "discovery",
      "experiment",
      "peer reviewed",
      "observatory",
    ],
    keyPhrases: [
      "new study",
      "research team",
      "scientific discovery",
      "published in",
    ],
  },
  {
    slug: "climate",
    displayName: "Climate",
    description: "Climate change, emissions, extreme weather, and environmental response.",
    aliases: ["climate change", "environment"],
    keywords: [
      "climate",
      "emissions",
      "carbon",
      "warming",
      "wildfire",
      "flooding",
      "drought",
      "storm",
      "hurricane",
      "environment",
      "heatwave",
    ],
    keyPhrases: [
      "climate change",
      "extreme weather",
      "carbon emissions",
      "climate policy",
    ],
  },
  {
    slug: "energy",
    displayName: "Energy",
    description: "Oil, gas, power grids, renewables, and energy infrastructure.",
    aliases: ["power", "energy sector"],
    keywords: [
      "energy",
      "oil",
      "gas",
      "electricity",
      "power",
      "grid",
      "renewable",
      "solar",
      "wind",
      "nuclear",
      "utility",
    ],
    keyPhrases: [
      "power grid",
      "oil prices",
      "renewable energy",
      "natural gas",
    ],
  },
  {
    slug: "defense",
    displayName: "Defense",
    description: "Military operations, national security, weapons, and defense strategy.",
    aliases: ["military", "national security"],
    keywords: [
      "defense",
      "military",
      "troops",
      "army",
      "navy",
      "air force",
      "missile",
      "weapon",
      "weapons",
      "security assistance",
      "pentagon",
    ],
    keyPhrases: [
      "national security",
      "defense ministry",
      "military aid",
      "missile defense",
    ],
  },
  {
    slug: "education",
    displayName: "Education",
    description: "Schools, universities, student policy, and education funding.",
    aliases: ["schools", "higher education"],
    keywords: [
      "education",
      "school",
      "schools",
      "student",
      "students",
      "teacher",
      "teachers",
      "university",
      "college",
      "campus",
      "classroom",
    ],
    keyPhrases: [
      "school district",
      "student loans",
      "higher education",
      "education funding",
    ],
  },
  {
    slug: "transportation",
    displayName: "Transportation",
    description: "Airlines, rail, transit, shipping, roads, and travel infrastructure.",
    aliases: ["transit", "travel infrastructure"],
    keywords: [
      "transportation",
      "transit",
      "airline",
      "airport",
      "rail",
      "train",
      "shipping",
      "port",
      "highway",
      "traffic",
      "aviation",
    ],
    keyPhrases: [
      "public transit",
      "air traffic",
      "supply chain",
      "transportation department",
    ],
  },
];

export const TOPIC_CATALOG_BY_SLUG = new Map(
  TOPIC_CATALOG.map((topic) => [topic.slug, topic]),
);
