export type TopicCatalogEntry = {
  slug: string;
  displayName: string;
  description: string;
  aliases: string[];
  keywords: string[];
  keyPhrases: string[];
  excludePhrases?: string[];
};

export const TOPIC_CATALOG: TopicCatalogEntry[] = [
  {
    slug: "politica",
    displayName: "Politică",
    description:
      "Instituții publice, partide, guvernare, alegeri și decizii politice interne.",
    aliases: ["politică internă", "guvernare", "partide"],
    keywords: [
      "politica",
      "politic",
      "guvern",
      "guvernul",
      "executiv",
      "parlament",
      "senat",
      "deputati",
      "deputați",
      "coalitie",
      "coaliție",
      "partid",
      "partide",
      "presedinte",
      "președinte",
      "premier",
      "ministru",
      "ministri",
      "miniștri",
      "alegeri",
      "vot",
      "campanie",
    ],
    keyPhrases: [
      "guvernul romaniei",
      "guvernul româniei",
      "coalitia de guvernare",
      "coaliția de guvernare",
      "camera deputatilor",
      "camera deputaților",
      "alegeri prezidentiale",
      "alegeri prezidențiale",
      "partid politic",
      "vot de incredere",
      "vot de încredere",
    ],
  },
  {
    slug: "economie",
    displayName: "Economie",
    description:
      "Buget, taxe, inflație, companii, piețe, muncă și evoluții macroeconomice.",
    aliases: ["economic", "afaceri", "finanțe"],
    keywords: [
      "economie",
      "economic",
      "buget",
      "taxe",
      "impozit",
      "impozite",
      "tva",
      "inflatie",
      "inflație",
      "preturi",
      "prețuri",
      "salarii",
      "pensii",
      "banca",
      "bănci",
      "bnr",
      "deficit",
      "piata",
      "piața",
      "companie",
      "companii",
      "profit",
      "investitii",
      "investiții",
      "energie",
      "carburanti",
      "carburanți",
    ],
    keyPhrases: [
      "crestere economica",
      "creștere economică",
      "deficit bugetar",
      "piata muncii",
      "piața muncii",
      "banca nationala",
      "banca națională",
      "preturile la energie",
      "prețurile la energie",
    ],
  },
  {
    slug: "externe",
    displayName: "Externe",
    description:
      "Relații internaționale, conflicte, diplomație, UE, NATO și evenimente din afara României.",
    aliases: ["internațional", "lume", "relații externe"],
    keywords: [
      "extern",
      "externe",
      "international",
      "internațional",
      "diplomatie",
      "diplomație",
      "ue",
      "uniunea europeana",
      "uniunea europeană",
      "nato",
      "sua",
      "ucraina",
      "ukraina",
      "rusia",
      "moldova",
      "bruxelles",
      "razboi",
      "război",
      "conflict",
      "sanctiuni",
      "sancțiuni",
      "ambasada",
      "ambasadă",
      "summit",
    ],
    keyPhrases: [
      "uniunea europeana",
      "uniunea europeană",
      "secretarul general nato",
      "ministerul de externe",
      "relatii internationale",
      "relații internaționale",
      "razboiul din ucraina",
      "războiul din ucraina",
    ],
  },
  {
    slug: "justitie",
    displayName: "Justiție",
    description:
      "Instanțe, anchete, dosare penale, procurori, legislație și decizii juridice.",
    aliases: ["justiție", "instanțe", "dosare penale"],
    keywords: [
      "justitie",
      "justiție",
      "instanta",
      "instanță",
      "instante",
      "instanțe",
      "judecator",
      "judecător",
      "procuror",
      "procurori",
      "dna",
      "diicot",
      "iccj",
      "proces",
      "dosar",
      "condamnare",
      "sentinta",
      "sentință",
      "rechizitoriu",
      "ancheta",
      "anchetă",
      "coruptie",
      "corupție",
      "lege",
      "legal",
    ],
    keyPhrases: [
      "curtea constitutionala",
      "curtea constituțională",
      "inalta curte",
      "înalta curte",
      "dosar penal",
      "urmarire penala",
      "urmărire penală",
      "control judiciar",
    ],
  },
  {
    slug: "sanatate",
    displayName: "Sănătate",
    description:
      "Sistem medical, spitale, pacienți, medicamente, epidemii și politici de sănătate publică.",
    aliases: ["sănătate publică", "medical", "spitale"],
    keywords: [
      "sanatate",
      "sănătate",
      "medical",
      "medic",
      "medici",
      "spital",
      "spitale",
      "pacient",
      "pacienti",
      "pacienți",
      "boala",
      "boală",
      "boli",
      "epidemie",
      "infectie",
      "infecție",
      "vaccin",
      "medicament",
      "medicamente",
      "tratament",
      "ambulanta",
      "ambulanță",
      "ministerul sanatatii",
      "ministerul sănătății",
    ],
    keyPhrases: [
      "sistemul medical",
      "sistemul de sanatate",
      "sistemul de sănătate",
      "spitalul judetean",
      "spitalul județean",
      "ministerul sanatatii",
      "ministerul sănătății",
    ],
  },
  {
    slug: "educatie",
    displayName: "Educație",
    description:
      "Școli, universități, elevi, studenți, profesori, examene și politici educaționale.",
    aliases: ["învățământ", "școală", "universități"],
    keywords: [
      "educatie",
      "educație",
      "invatamant",
      "învățământ",
      "scoala",
      "școala",
      "scoli",
      "școli",
      "elev",
      "elevi",
      "student",
      "studenti",
      "studenți",
      "profesor",
      "profesori",
      "universitate",
      "universitati",
      "universități",
      "bacalaureat",
      "evaluare",
      "examen",
      "examene",
      "burse",
    ],
    keyPhrases: [
      "ministerul educatiei",
      "ministerul educației",
      "anul scolar",
      "anul școlar",
      "evaluarea nationala",
      "evaluarea națională",
      "examenul de bacalaureat",
    ],
  },
  {
    slug: "tehnologie",
    displayName: "Tehnologie",
    description:
      "Tehnologie, internet, securitate cibernetică, inteligență artificială, software și produse digitale.",
    aliases: ["tech", "digital", "inteligență artificială"],
    keywords: [
      "tehnologie",
      "tehnologic",
      "digital",
      "internet",
      "online",
      "software",
      "aplicatie",
      "aplicație",
      "platforma",
      "platformă",
      "telefon",
      "smartphone",
      "cip",
      "cipuri",
      "semiconductor",
      "inteligenta",
      "inteligență",
      "artificiala",
      "artificială",
      "ai",
      "ia",
      "algoritm",
      "algoritmi",
      "cibernetic",
      "hacker",
      "date",
    ],
    keyPhrases: [
      "inteligenta artificiala",
      "inteligență artificială",
      "securitate cibernetica",
      "securitate cibernetică",
      "atac cibernetic",
      "date personale",
      "retele sociale",
      "rețele sociale",
    ],
  },
  {
    slug: "sport",
    displayName: "Sport",
    description:
      "Competiții sportive, fotbal, tenis, handbal, rezultate, sportivi și cluburi.",
    aliases: ["fotbal", "competiții sportive", "rezultate sportive"],
    keywords: [
      "sport",
      "sportiv",
      "sportivi",
      "fotbal",
      "meci",
      "meciuri",
      "echipa",
      "echipă",
      "club",
      "campionat",
      "liga",
      "superliga",
      "tenis",
      "handbal",
      "baschet",
      "olimpic",
      "olimpica",
      "olimpică",
      "medalie",
      "antrenor",
      "stadion",
      "gol",
    ],
    keyPhrases: [
      "echipa nationala",
      "echipa națională",
      "liga campionilor",
      "jocurile olimpice",
      "campionatul mondial",
      "campionatul european",
    ],
  },
  {
    slug: "cultura",
    displayName: "Cultură",
    description:
      "Arte, film, muzică, literatură, patrimoniu, festivaluri și evenimente culturale.",
    aliases: ["arte", "film", "muzică"],
    keywords: [
      "cultura",
      "cultură",
      "cultural",
      "arta",
      "artă",
      "artist",
      "artisti",
      "artiști",
      "film",
      "cinema",
      "muzica",
      "muzică",
      "concert",
      "festival",
      "teatru",
      "muzeu",
      "literatura",
      "literatură",
      "carte",
      "carti",
      "cărți",
      "patrimoniu",
      "expozitie",
      "expoziție",
    ],
    keyPhrases: [
      "festival de film",
      "festivalul international",
      "festivalul internațional",
      "ministerul culturii",
      "patrimoniu cultural",
      "premiera filmului",
      "premiera filmului",
    ],
  },
  {
    slug: "social",
    displayName: "Social",
    description:
      "Comunități, siguranță publică, familie, locuire, proteste, drepturi sociale și viață cotidiană.",
    aliases: ["societate", "comunități", "viață socială"],
    keywords: [
      "social",
      "societate",
      "comunitate",
      "comunitati",
      "comunități",
      "familie",
      "copii",
      "locuinte",
      "locuințe",
      "chirii",
      "saracie",
      "sărăcie",
      "ajutor",
      "protest",
      "proteste",
      "greva",
      "grevă",
      "politisti",
      "polițiști",
      "accident",
      "trafic",
      "drepturi",
      "violenta",
      "violență",
    ],
    keyPhrases: [
      "asistenta sociala",
      "asistență socială",
      "protectia copilului",
      "protecția copilului",
      "siguranta publica",
      "siguranță publică",
      "protest in bucuresti",
      "protest în bucurești",
    ],
  },
  {
    slug: "mediu",
    displayName: "Mediu",
    description:
      "Mediu, climă, poluare, energie verde, fenomene meteo extreme și protecția naturii.",
    aliases: ["climă", "ecologie", "protecția mediului"],
    keywords: [
      "mediu",
      "clima",
      "climă",
      "ecologie",
      "poluare",
      "deseuri",
      "deșeuri",
      "reciclare",
      "padure",
      "pădure",
      "paduri",
      "păduri",
      "inundatii",
      "inundații",
      "seceta",
      "secetă",
      "canicula",
      "caniculă",
      "furtuna",
      "furtună",
      "emisie",
      "emisii",
      "verde",
      "regenerabil",
    ],
    keyPhrases: [
      "schimbari climatice",
      "schimbări climatice",
      "protectia mediului",
      "protecția mediului",
      "garda de mediu",
      "energie regenerabila",
      "energie regenerabilă",
      "cod rosu de canicula",
      "cod roșu de caniculă",
    ],
  },
];

export const TOPIC_CATALOG_BY_SLUG = new Map(
  TOPIC_CATALOG.map((topic) => [topic.slug, topic]),
);

export const TOPIC_CATALOG_SLUGS = new Set(
  TOPIC_CATALOG.map((topic) => topic.slug),
);
